### ISSUE TITLE
multinode-smoothbrain-backup.sh errors

### ISSUE THREAD

**Issue by haroldboom** [calr0x/OT-2Nodes1Server#130]
Hey boys,

multinode-smoothbrain-backup.sh has some syntax errors, it mentions OT-settings for the send.sh location, it should be OT-2Nodes1Server. See below;

  echo "Uploading $NODE data to storage server"
  OUTPUT=$(/root/OT-2Nodes1Server/restic backup --tag $NODE /root/backup/.origintrail_noderc /root/backup/* 2>&1)
  if [ $STATUS -eq 0 ]; then
    /root/**OT-Settings**/data/$SEND.sh "Backup SUCCESSFUL:${N1}$OUTPUT"
    rm -rf /root/backup
  else
    /root/**OT-Settings/**data/$SEND.sh "Uploading backup to storage VPS FAILED:${N1}$OUTPUT"
    exit 1
  fi

**Comment by haroldboom** [comment]
Also an issue at line 72;

./multinode-smoothbrain-backup.sh: line 64: /root/OT-Settings/data/send3.sh: No such file or directory
./multinode-smoothbrain-backup.sh: line 72: syntax error near unexpected token `fi'
./multinode-smoothbrain-backup.sh: line 72: ` fi'

**Comment by Valcyclovir** [comment]
solved ! thanks
