### ISSUE TITLE
Git Pull .sh name changes didn't update crontab

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-2Nodes1Server#136]
Crontab still refers to the old names:

*/60 * * * * /root/OT-2Nodes1Server/multinode-monitor.sh
0 0 * * * /root/OT-2Nodes1Server/multinode-coldbrain-backup.sh

Need to update crontab for the new name changes.

**Comment by Valcyclovir** [comment]
you will have to edit your crontab manually for this one, and I changed it on the readme to reflect the new names ! Thanks
