### ISSUE TITLE
Backup Instructions for linking to Storage Server only refer to Coldbrain

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-2Nodes1Server#137]
Can we have a smoothbrain option as well? I assume just swap out the crontab line for smoothbrain.sh?

I trust smoothbrain more than coldbrain for restores so would like to use that one.

**Comment by Valcyclovir** [comment]
I will add this part a bit later tonight, the script for normal smoothbrain restore is available, so you can still use it for the time being !

**Comment by Valcyclovir** [comment]
You can swap the crontab line to cronjob-smoothbrain-backup.sh
