### ISSUE TITLE
cronjob-smoothbrain-backup.sh only backing up one node

### ISSUE THREAD

**Issue by haroldboom** [calr0x/OT-2Nodes1Server#138]
Hey BRX,

It looks like something has changed with the last pull, I am only getting one node backing up and no notification of success. Might be because of AWS but I am not sure. Attached is the output from the script
[backuplog.txt](https://github.com/calr0x/OT-2Nodes1Server/files/7024532/backuplog.txt)

**Comment by Valcyclovir** [comment]
thanks for the logs and error is fixed ! git pull away
