### ISSUE TITLE
(OPTIONAL III) SQLITE_CORRUPT BUG : SCP from old node to Multi Server

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-2Nodes1Server#222]
For those that have permission issues SCP from Multi to old node, do it in reverse:

scp /root/system.db.backup root@REPLACE_WITH_MULTI_NODE_IP:/root

Then mv from root to the right directory and replace system.db with the backup file

**Comment by Valcyclovir** [comment]
readme section modified to address this !
