### ISSUE TITLE
Request: Amazon Backup

### ISSUE THREAD

**Issue by haroldboom** [calr0x/OT-2Nodes1Server#78]
Hey guys,

Would it be possible to add Amazon AWS for a backup option? Thanks for all your hard work

**Comment by Valcyclovir** [comment]
Although I don't recommend it, the support is added back on the config-example.sh file. You actually don't have to change anything besides
export RESTIC_REPOSITORY=s3:https://s3.amazonaws.com/bucketname

My scripts will all work fine with either a storage VPS or Amazon AWS !
