### ISSUE TITLE
Some of the lines of code to copy paste with the copy button have spaces

### ISSUE THREAD

**Issue by hottogo** [calr0x/OT-2Nodes1Server#80]
I think this one was one of them, I ran into it several times:

scp -r /root/OT-2Nodes1Server remote_username@server_ip_address:/root/OT-2Nodes1Server

They have a space at the end or something, so you can't edit it in the console to add in your details, it auto runs.

**Comment by Valcyclovir** [comment]
Unfortunately it's just how it is, you'd have to highlight the entire line and copy it, paste it on your console to edit it.

Or open a notepad on the side, paste it there, then after modifying, paste it in the command. 

Cheers and thanks for your support !
